force-app/main/default/objects/BRD_Rule__c/BRD_Rule__c.object-meta.xml
<CustomObject>
    <description>BRD Rule,Category,Sub-Category</description>
    <label>BRD Rule</label>
    <nameField>
        <label>BRD Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BRD Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Parameter__c/Global_Parameter__c.object-meta.xml
<CustomObject>
    <label>Global Parameter</label>
    <nameField>
        <label>Global Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Screen_Progress__c.field-meta.xml
<CustomField>
    <fullName>Screen_Progress__c</fullName>
    <label>Screen Progress</label>
    <referenceTo>Screen_Progress__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Customize_Detail__c.field-meta.xml
<CustomField>
    <fullName>Customize_Detail__c</fullName>
    <label>Customize Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Number__c</fullName>
    <label>Question Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Title__c.field-meta.xml
<CustomField>
    <fullName>Question_Title__c</fullName>
    <label>Question Title</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/BRD_Rule__c.field-meta.xml
<CustomField>
    <fullName>BRD_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BRD Rule</label>
    <referenceTo>BRD_Rule__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>category</label>
    <referenceTo>BRD_Rule__c</referenceTo>
    <relationshipLabel>Question Choices (category)</relationshipLabel>
    <relationshipName>Question_Choices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/Global_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Global_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Parameter</label>
    <referenceTo>Global_Parameter__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Buttons__c.field-meta.xml
<CustomField>
    <fullName>Show_Buttons__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Buttons</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Show_Module_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Module Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ZEC_QuestionDAO.cls
public class ZEC_QuestionDAO {
    
    public static List<Question__c> Question_By_Active_Screen_Project(Boolean isActive,String screenId,String projectId){
        return [SELECT Id, Description__c, Name, Module_Progress__r.Module__r.Name,Module_Progress__c,
         Module_Progress__r.Module__r.Category__r.Name,Customize_Detail__c
         ,Module_Progress__r.Screen_Progress__r.Screen__r.Name, Is_Active__c, Question_Number__c, 
         Question_Title__c, Question_Type__c, Image__c,Module_Progress__r.Screen_Progress__r.Show_Buttons__c,Module_Progress__r.Screen_Progress__r.Show_Module_Progress__c,
         (SELECT Id, Question__c, Global_Parameter__c, Default__c, Description__c, Name from Question_Choices__r)
         FROM Question__c where Module_Progress__r.Screen_Progress__r.Screen__c=:screenId and Is_Active__c =:isActive and Module_Progress__r.Screen_Progress__r.Project__c =:projectId order by question_Number__c];
    }
    
    public static Question__c getQuestion_By_Id(String questionId){
        return [Select id,Customize_Detail__c from Question__c where id=:questionId];
    }

    
    public static void update_Question(Question__c questionRecord){
        update questionRecord;
    }
}