force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Title__c.field-meta.xml
<CustomField>
    <fullName>Question_Title__c</fullName>
    <label>Question Title</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question_Choice__c.field-meta.xml
<CustomField>
    <fullName>Question_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Choice</label>
    <referenceTo>Question_Choice__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZEC_QuestionResponseDAO.cls
public with sharing class ZEC_QuestionResponseDAO {
    public static List<Question_Response__c> getQuestionResponseByScreen(String projectId, String screenName, Integer recordLimit){
        return [SELECT Id, Name, Question__c, Question__r.Question_Title__c,Question__r.Description__c, Question_Choice__r.Name 
                FROM Question_Response__c 
                /*WHERE Question__r.Screen__c =: screenName and Question__r.Project__c =: projectId*/ 
                ORDER BY CreatedDate,Question__c desc LIMIT :recordLimit];
    }
    
    public static List<Question_Response__c> getQuesResponses_By_Question(List<Question__c> questions){
       return [Select Id,Question_Choice__r.Question__c, Question_Choice__r.Name,Question_Choice__c, Project__c, Comment__c 
               FROM Question_Response__c WHERE Question_Choice__r.Question__c in:questions];
    }
    
    public static void delete_QuestionResponses_By_QuestionIds(List<Id> questionIds ){
        delete [Select id from Question_Response__c where Question__c in :questionIds];
    }
    
    public static List<Question_Response__c> insert_Responses(List<Question_Response__c> questionResponses){
        insert questionResponses;
        return questionResponses;
    }
}