force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Get_Sign_Off__c.field-meta.xml
<CustomField>
    <fullName>Get_Sign_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get Sign Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <inlineHelpText>Order of displaying the screens</inlineHelpText>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Buttons__c.field-meta.xml
<CustomField>
    <fullName>Show_Buttons__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Buttons</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Show_Module_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Module Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Summary__c.field-meta.xml
<CustomField>
    <fullName>Show_Summary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not-Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ZEC_ScreenProgressDAO.cls
public with sharing class ZEC_ScreenProgressDAO {
    public static List<Screen_Progress__c> getScreensByProject(String projectId){
        return [SELECT Id, Name, Get_Sign_Off__c, Project__c, Screen_Order__c, Show_Summary__c, 
                Status__c, Account__c, Screen__c, Show_Module_Progress__c, Show_Buttons__c,Screen__r.Name
                FROM Screen_Progress__c
                WHERE Project__c =: projectId ORDER BY Screen_Order__c ASC];
    }

    public static List<Screen_Progress__c> upsertRecord(List<Screen_Progress__c> listOfScreenProgress){
        upsert listOfScreenProgress;
        return listOfScreenProgress;
    }
}