force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZEC_UserDAO.cls
public class ZEC_UserDAO {

    public static List<User> getUsers_By_Id(String userId){
        return [Select id,Client__c,Project__c from User where id=:userId];
    }
    
    public static void update_AccountClientOnUser(String userId,String accountId,String projectId){
        User userRecord = new User();
        userRecord.Id = userId;
        userRecord.Client__c = accountId;
        userRecord.Project__c = projectId;
        update userRecord;
    }
}