force-app/main/default/objects/Action_Item__c/Action_Item__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Parameter__c/Global_Parameter__c.object-meta.xml
<CustomObject>
    <label>Global Parameter</label>
    <nameField>
        <label>Global Parameter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Screen_Progress__c.field-meta.xml
<CustomField>
    <fullName>Screen_Progress__c</fullName>
    <label>Screen Progress</label>
    <referenceTo>Screen_Progress__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Number__c</fullName>
    <label>Question Number</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Title__c.field-meta.xml
<CustomField>
    <fullName>Question_Title__c</fullName>
    <label>Question Title</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/Global_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Global_Parameter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Parameter</label>
    <referenceTo>Global_Parameter__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question_Choice__c.field-meta.xml
<CustomField>
    <fullName>Question_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Choice</label>
    <referenceTo>Question_Choice__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <inlineHelpText>Order of displaying the screens</inlineHelpText>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Show_Module_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Module Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Summary__c.field-meta.xml
<CustomField>
    <fullName>Show_Summary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not-Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ZEC_ScreenProgressController.cls
public with sharing class ZEC_ScreenProgressController {
    public ZEC_ScreenProgressController() {

    }

    @AuraEnabled
    public static Map<String, Object> getScreenProgressData(String projectId){
        System.debug('projectId'+projectId);
        List<Screen_Progress__c> listOfScreens = getScreens(projectId);
        Screen_Progress__c currentScreen;
        Integer count= 0;
        for(Screen_Progress__c screen : listOfScreens){
            if(screen.Status__c == 'In Progress' && screen.Show_Summary__c){
                currentScreen = screen;
                break;
            }
            else if(screen.Status__c == 'Not-Started' && screen.Show_Summary__c){
                currentScreen = screen;
                break;
            }
            else if(screen.Status__c == 'Completed' && screen.Show_Summary__c){
                count +=1;
            }
        }

        if(currentScreen == null){
            currentScreen = listOfScreens[count - 1];
        }

        Map<String, Object> mapOfData = new Map<String, Object>();
        mapOfData.put('currentScreen', currentScreen);
        mapOfData.put('moduleTree', moduleTree(listOfScreens));
        mapOfData.put('screenProgress',screenProgress(projectId, currentScreen.Name));
        mapOfData.put('getAlerts',getAlerts(projectId, currentScreen.Name));
        mapOfData.put('getRecentAnsweredQuestions',getRecentAnsweredQuestions(projectId, currentScreen.Name));
        return mapOfData;
    } 
    
    @AuraEnabled
    public static List<moduleProgressTreeData> moduleTreeComponent(String projectId){
        return moduleTree(getScreens(projectId));
    }
    
    public static List<moduleProgressTreeData> moduleTree(List<Screen_Progress__c> screens){
        List<moduleProgressTreeData> moduleProgress =  new List<moduleProgressTreeData>();
        for(Screen_Progress__c rec : screens){
            moduleProgressTreeData record = new moduleProgressTreeData();
            record.stepName = 'Step '+rec.Screen_Order__c;
            record.screenName = rec.Name;
            if(rec.Status__c == 'In Progress'){
                record.activeStep = 'active-step';
            }
            if(rec.Status__c == 'Completed'){
                record.stepCompleted = 'success';
            }
            if(rec.Show_Module_Progress__c){
                record.showModuleProgress = true;
            }
            record.screenProgress = rec;
            moduleProgress.add(Record);
        }
        return moduleProgress;
    }
    
    public class moduleProgressTreeData{
        @AuraEnabled public String stepName;
        @AuraEnabled public String screenName;
        @AuraEnabled public String activeStep = '';
        @AuraEnabled public String stepCompleted = '';
        @AuraEnabled public boolean showModuleProgress = false;
        @AuraEnabled public Screen_Progress__c screenProgress ;
    }

    @AuraEnabled
    public static List<Screen_Progress__c> getScreens(String projectId){
        if(projectId == null) { projectId ='a012w00000yncTfAAI'; }
        return ZEC_ScreenProgressDAO.getScreensByProject(projectId);
    }

    @AuraEnabled
    public static List<Screen_Progress__c> updateStatus(String screenProgressJSON){
        Screen_Progress__c screenProgressRecord = (Screen_Progress__c)JSON.deserialize(screenProgressJSON, Screen_Progress__c.class);
        List<Screen_Progress__c> listOfScreenProgress = ZEC_ScreenProgressDAO.upsertRecord(new List<Screen_Progress__c>{screenProgressRecord});
        return getScreens(null);
    }
    
    @AuraEnabled
    public static ProgressRateWrapper screenProgress(String projectId, String screenName){
        List<Question__c> questions = new List<Question__c>();
        questions = [SELECT Id, Description__c, Name, Module_Progress__c,Module_Progress__r.Module__r.Name, Is_Active__c, Question_Number__c, Question_Title__c, Question_Type__c, Image__c,
                (SELECT Id, Question__c, Global_Parameter__c, Default__c, Description__c, Name from Question_Choices__r)
                FROM Question__c where Module_Progress__r.Screen_Progress__r.Screen__r.Name=:screenName and Is_Active__c = true and Module_Progress__r.Screen_Progress__r.Project__c =:projectId order by question_Number__C];
        List<AggregateResult> responses = [SELECT Question__c FROM Question_Response__c where Question__c in:questions group by Question__c ];

        ProgressRateWrapper record = new ProgressRateWrapper();
        record.NumberOfQuestions = questions.Size();
        record.NumberOfResponses = responses.Size();
        record.CompletionRate = questions.Size()>0?((responses.Size()*100)/questions.Size()):0;
       
        return record;
    }

    public static List<Action_Item__c> getAlerts(String projectId, String screenName){
        return ZEC_ActionItemDAO.getActionItemsByScreen(projectId, screenName);
    }

    public static List<RecentlyAnsweredQuestionWrapper> getRecentAnsweredQuestions(String projectId, String screenName){
        List<Question_Response__c> listOfQuestionResponses = ZEC_QuestionResponseDAO.getQuestionResponseByScreen(projectId, screenName, 5);

        Map<Id, List<Question_Response__c>> mapOfQuestionResponse = new Map<Id, List<Question_Response__c>>();
        for(Question_Response__c questionResponse : listOfQuestionResponses){
            If(mapOfQuestionResponse.containsKey(questionResponse.Question__c)){
                List<Question_Response__c> listOfQuestionResponse = (List<Question_Response__c>)mapOfQuestionResponse.get(questionResponse.Question__c);
                listOfQuestionResponse.add(questionResponse);
            }
            else{
                mapOfQuestionResponse.put(questionResponse.Question__c, new List<Question_Response__c>{questionResponse});
            }
        }

        List<RecentlyAnsweredQuestionWrapper> listOfRecentlyAnsweredQuestion = new List<RecentlyAnsweredQuestionWrapper>();
        for(Id questionId : mapOfQuestionResponse.keySet()){
            List<Question_Response__c> listOfQuestionResponse = mapOfQuestionResponse.get(questionId);
            RecentlyAnsweredQuestionWrapper recentAnsweredRecord = new RecentlyAnsweredQuestionWrapper();
            recentAnsweredRecord.questionId = questionId;
            List<String> listOfAnswers = new List<String>();
            for(Question_Response__c questionResponse : listOfQuestionResponse){
                listOfAnswers.add(questionResponse.Question_Choice__r.Name);
                recentAnsweredRecord.question = questionResponse.Question__r.Question_Title__c;
            }
            recentAnsweredRecord.answer = String.join(listOfAnswers, ',');
            listOfRecentlyAnsweredQuestion.add(recentAnsweredRecord);
        }
        return listOfRecentlyAnsweredQuestion;
    }

    public class RecentlyAnsweredQuestionWrapper{
        @AuraEnabled public Id questionId { get; set; }
        @AuraEnabled public String question { get; set; }
        @AuraEnabled public String answer { get; set; }
    }
    
    public class ProgressRateWrapper{
        @AuraEnabled public Integer NumberOfQuestions { get; set; }
        @AuraEnabled public Integer NumberOfResponses { get; set; }
        @AuraEnabled public Decimal CompletionRate { get; set; }
    }
}