force-app/main/default/objects/Account/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <label>Module</label>
</RecordType>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Screen_Progress__c.field-meta.xml
<CustomField>
    <fullName>Screen_Progress__c</fullName>
    <label>Screen Progress</label>
    <referenceTo>Screen_Progress__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Client_brands__c.field-meta.xml
<CustomField>
    <fullName>Client_brands__c</fullName>
    <label>Client brands</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Competitor_brands__c.field-meta.xml
<CustomField>
    <fullName>Competitor_brands__c</fullName>
    <label>Competitor brands</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Focused_HCO__c.field-meta.xml
<CustomField>
    <fullName>Focused_HCO__c</fullName>
    <label>Focused HCO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Focused_HCP__c.field-meta.xml
<CustomField>
    <fullName>Focused_HCP__c</fullName>
    <label>Focused HCP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Module__c/Project_Module__c.object-meta.xml
<CustomObject>
    <label>Project Module</label>
    <nameField>
        <label>Project Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Module</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Project Module</relationshipLabel>
    <relationshipName>Project_Module</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Module__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Module</relationshipLabel>
    <relationshipName>Project_Module</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_User__c/Project_User__c.object-meta.xml
<CustomObject>
    <label>Project User</label>
    <nameField>
        <label>Project User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project User</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_User__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project User</relationshipLabel>
    <relationshipName>Project_User</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Get_Sign_Off__c.field-meta.xml
<CustomField>
    <fullName>Get_Sign_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get Sign Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <inlineHelpText>Order of displaying the screens</inlineHelpText>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Summary__c.field-meta.xml
<CustomField>
    <fullName>Show_Summary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZEC_ClientOnboardingController.cls
public class ZEC_ClientOnboardingController {
public ZEC_ClientOnboardingController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<SObJectResult> getResults(String ObjectName, String fieldName, String value, List<String> selectedRecId) {
        List<SObJectResult> sObjectResultList = new List<SObJectResult>();
        system.debug(fieldName+'-------------'+ObjectName+'---++----------'+value+'====='+selectedRecId);
        if(selectedRecId == null)
            selectedRecId = new List<String>();

        if(String.isNotEmpty(value)) {
            String query = 'Select Id,'+fieldName+' FROM '+ObjectName+' WHERE '+fieldName+' LIKE \'%' + value.trim() + '%\' and ID NOT IN: selectedRecId';
            system.debug(query);
            for(sObject so : Database.Query(query)) {
                String fieldvalue = (String)so.get(fieldName);
                sObjectResultList.add(new SObjectResult(fieldvalue, so.Id));
            }
        }
        return sObjectResultList;
    }
    
    public class SObjectResult {
        @AuraEnabled
        public String recName;
        @AuraEnabled
        public Id recId;
        
        public SObJectResult(String recNameTemp, Id recIdTemp) {
            recName = recNameTemp;
            recId = recIdTemp;
        }
        public SObJectResult() {
          
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<sObject> getModules(){
        try {
            List<sObject> m_Types = new List<sObject>();
             
            m_Types = [Select id, Name from Module__c]; 
             
            return m_Types;
        } catch (Exception e) {
            System.debug('Exception: '+e.getMessage());
            return null;
        }
    }
	@AuraEnabled
    public static List<ProjectWrapper> deleteProject(string projectId){
		delete [SELECT id from Project_User__c where Project__c =:projectId];
		delete [SELECT id from Project_Module__c where Project__c =:projectId];
		delete [SELECT id from Project__c where id =:projectId];
		return retrieveAccounts();
	}
	@AuraEnabled
    public static List<Project__c> showProject(string projectId){
		List<Project__c> projList = [SELECT id, Name,LastModifiedDate, LastModifiedBy.Name, Client__r.Name,(select id, Module__r.Name from Project_Module__r),(select id, User__r.Id,User__r.Name from Project_User__r) from Project__c where id=:projectId];
		return projList;
	}
	@AuraEnabled
    public static void updateProject(string projectName, List<string> modules,string users, string projectId){
		delete [SELECT id from Project_User__c where Project__c =:projectId];
		delete [SELECT id from Project_Module__c where Project__c =:projectId];
       List<object> userMap = (List<object>)JSON.deserializeUntyped(users);
	   List<Project_Module__c> pmList = new List<Project_Module__c>();
		List<Module__c> mList = [Select id, Name from Module__c where id IN : modules]; 
		for(Module__c m : mList){
			Project_Module__c pm = new Project_Module__c();
			pm.Module__c = m.Id;
			pm.Name = m.Name;
			pm.Project__c = projectId;
			pmList.add(pm);
		}
		
	   List<Project_User__c> puList =  new List<Project_User__c>();
	   for(object o : userMap){
            Map<string, object> newUserMap = new Map<string,object>();
            newUserMap=(Map<string,object>)o;
			Project_User__c pu =  new Project_User__c();
			pu.User__c = (String)newUserMap.get('recId');
			pu.Project__c = projectId;
			pu.Name = (String)newUserMap.get('recName');
			puList.add(pu);
		}
		insert pmList;
		insert puList;
    }
	
	@AuraEnabled
    public static void saveProject(string clientId, string projectName, List<string> modules, string users, string competitorBrand,string focusedHco, string focusedHcp, string clientBrand, string fileRecordId){
		
        List<object> userMap = (List<object>)JSON.deserializeUntyped(users);
		
        
        Project__c pr = new Project__c();
		pr.Client__c = clientId; // accountId
		pr.Name = projectName;
		pr.Competitor_brands__c = competitorBrand;
		pr.Focused_HCO__c = focusedHco;
		pr.Focused_HCP__c = focusedHcp;
		pr.Client_brands__c = clientBrand;
		pr.Logo__c = fileRecordId;
        system.debug('modules'+modules);
        system.debug('users'+users);
		insert pr;
        
        
        List<Screen__c> screenList = [Select Id, Name, Get_Sign_Off__c, Show_Summary__c, Screen_Order__c from Screen__c];
        List<Screen_Progress__c> screenProgressList = createScreenProgress(screenList, pr);
        insert screenProgressList;
        Map<Id, Screen_Progress__c> screenProgressMap = new Map<Id, Screen_Progress__c>();
        for(Screen_Progress__c screenProgress : screenProgressList){
            screenProgressMap.put(screenProgress.Screen__c, screenProgress);
        }
        List<Module__c> moduleList = [Select id, Name, Screen__c from Module__c where id IN : modules];
        List<Module_Progress__c> moduleProgressList = createModuleProgress(moduleList, screenProgressMap);
        insert moduleProgressList;
		// creating Project_modules for each selected modules
		/*List<Project_Module__c> pmList = new List<Project_Module__c>();
		List<Module__c> mList = [Select id, Name, Screen__c from Module__c where id IN : modules]; 
        
        
		for(Module__c m : mList){
			Project_Module__c pm = new Project_Module__c();
			pm.Module__c = m.Id;
			pm.Name = m.Name;
			pm.Project__c = pr.Id;
			pmList.add(pm);
		}*/
		//creating Project_User__c for each selected users
		List<Project_User__c> puList =  new List<Project_User__c>();
		for(object o : userMap){
            Map<string, object> newUserMap = new Map<string,object>();
            newUserMap=(Map<string,object>)o;
			Project_User__c pu =  new Project_User__c();
			pu.User__c = (String)newUserMap.get('recId');
			pu.Project__c = pr.Id;
			pu.Name = (String)newUserMap.get('recName');
			puList.add(pu);
		}
       
		//insert pmList;
		insert puList;
		
    }
    
    private static List<Screen_Progress__c> createScreenProgress(List<Screen__c> screenList, Project__c projectRecord){
        List<Screen_Progress__c> screenProgressList = new List<Screen_Progress__c>();
        for(Screen__c screen : screenList){
            Screen_Progress__c screenProgress = new Screen_Progress__c();
            screenProgress.Name = screen.Name;
            screenProgress.Get_Sign_Off__c = screen.Get_Sign_Off__c;
            screenProgress.Show_Summary__c = screen.Show_Summary__c;
            screenProgress.Screen_Order__c = screen.Screen_Order__c;
            screenProgress.Screen__c = screen.Id;
            screenProgress.Account__c = projectRecord.Client__c;
            screenProgress.Project__c = projectRecord.Id;
            screenProgressList.add(screenProgress);
        }
        return screenProgressList;
    }
    
    private static List<Module_Progress__c> createModuleProgress(List<Module__c> moduleList, Map<Id, Screen_Progress__c> screenProgressMap){
        List<Module_Progress__c> moduleProgressList = new List<Module_Progress__c>();
        for(Module__c module : moduleList){
            Module_Progress__c moduleProgress = new Module_Progress__c();
            moduleProgress.Name = module.Name;
            moduleProgress.Screen_Progress__c = screenProgressMap.get(module.Screen__c).Id;
            moduleProgressList.add(moduleProgress);
        }
        return moduleProgressList;
    }
    
    @AuraEnabled (cacheable=true)
    public static List<ProjectWrapper> retrieveAccounts(){
        List<ProjectWrapper> prWrapperList = new List<ProjectWrapper>();
		List<Project__c> projList = [SELECT id, Name,LastModifiedDate, LastModifiedBy.Name, Client__r.Name,(select id, Module__r.Name from Project_Module__r),(select id, User__r.Id,User__r.Name from Project_User__r) from Project__c order by LastModifiedDate desc];
		ProjectWrapper prWrap;
		Map<Id,List<Project_User__c>> projUserMap = new Map<Id,List<Project_User__c>>();
		for(Project__c p: projList){
			List<Project_User__c> prjUser = new List<Project_User__c>();
			for(Project_User__c pu: p.Project_User__r){
				prjUser.add(pu);
				projUserMap.put(p.id,prjUser);
			}
		}
		for(Project__c p: projList){
			prWrap = new ProjectWrapper();
			List<string> prjMod = new List<String>();
			List<string> prjUser = new List<String>();
			for(Project_Module__c pm : p.Project_Module__r){
				if(!prjMod.contains(pm.Module__r.Name)){
					prjMod.add(pm.Module__r.Name);
				}
			}
			for(Project_User__c pu: p.Project_User__r){
				if(!prjUser.contains(pu.User__r.Name)){
					prjUser.add(pu.User__r.Name);
				}
			}
			string prModule = string.join(prjMod,',');
			string prUser = string.join(prjUser,',');
			//String myDate = p.LastModifiedDate.format('d MMM yyyy hh:mm aaa'); 
			//string lastModifiedColumn = myDate + ' by '+ p.LastModifiedBy.Name;
			prWrap.prModuleList = prjMod; 
			prWrap.usersList = projUserMap.get(p.Id); 
			prWrap.projectName = p.Name; 
            prWrap.prId = p.Id;
            prWrap.clientName = p.Client__r.Name;
            prWrap.modules = prModule;
            prWrap.users = prUser;
            //prWrap.lastModified = lastModifiedColumn;
            prWrap.lastModifiedDate = p.LastModifiedDate;
            prWrap.lastModifiedName = p.LastModifiedBy.Name;
			prWrapperList.add(prWrap);
		}
        return prWrapperList;
    }
    public class ProjectWrapper {
        @AuraEnabled
        public String projectName;
        @AuraEnabled
        public Id prId;
		@AuraEnabled
        public String clientName;
        @AuraEnabled
        public String modules;
		@AuraEnabled
        public List<String> prModuleList;
		@AuraEnabled
        public String users;
		@AuraEnabled
        public List<Project_User__c> usersList;
		@AuraEnabled
        public DateTime lastModifiedDate;
        @AuraEnabled
        public String lastModifiedName;
        
       
        public ProjectWrapper() {
          
        }
    }

}