force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Criticality__c.field-meta.xml
<CustomField>
    <fullName>Criticality__c</fullName>
    <label>Criticality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Criticality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Question_Choice__c.field-meta.xml
<CustomField>
    <fullName>Question_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Choice</label>
    <referenceTo>Question_Choice__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item__c/Action_Item__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Criticality__c.field-meta.xml
<CustomField>
    <fullName>Criticality__c</fullName>
    <label>Criticality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Criticality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Details_to_capture__c.field-meta.xml
<CustomField>
    <fullName>Details_to_capture__c</fullName>
    <label>Details to capture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item_Response__c/Action_Item_Response__c.object-meta.xml
<CustomObject>
    <label>Action Item Response</label>
    <nameField>
        <label>Action Item Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Item Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item_Response__c/fields/Action_Item__c.field-meta.xml
<CustomField>
    <fullName>Action_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Item</label>
    <referenceTo>Action_Item__c</referenceTo>
    <relationshipLabel>Action Item Responses</relationshipLabel>
    <relationshipName>Action_Item_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Item_Response__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <label>Module</label>
</RecordType>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZEC_ActionItemController.cls
public with sharing class ZEC_ActionItemController {
	
	//public static final string BRD_RULE_TYPE = 'Rule Category';
	public static final string TOGGLE_ICON = 'utility:chevronright';
    
	@AuraEnabled( cacheable = true )
    public static List<ActionItemWrapper> fetchActionItems(string projectId) {
        system.debug('projectId '+projectId);
        List< ActionItemWrapper > actionItemWrap = new List< ActionItemWrapper >();
         
		for ( Action_Item__c actionItem : [ SELECT Id, OwnerId, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, 
									   SystemModstamp, LastActivityDate, Contact__c,Action__c,Action__r.Project__c, Details_to_capture__c, ETA__c, Response__c, 
									   Status__c,Contact__r.Name,Criticality__c,Action__r.Question_Choice__r.Question__r.Module_Progress__r.Module__r.Name,(SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, CreatedBy.Name, LastModifiedDate, LastModifiedById, SystemModstamp, Action_Item__c, ETA__c, Status__c, Comments__c, Response__c 
										FROM Action_Item_Responses__r) FROM Action_Item__c WHERE Action__r.Project__c =:projectId AND Name != NULL ] ) {
																					 
										 //ActionItemWrapper objWrap = new ActionItemWrapper( true, actionItem, actionItem.Contacts.size() > 0 ? true : false );
										 ActionItemWrapper objWrap = new ActionItemWrapper( true, false, actionItem, true ,TOGGLE_ICON);
										 actionItemWrap.add( objWrap );
																					 
		}
        
        return actionItemWrap;
        
    }
    @AuraEnabled( cacheable = true )
    public static List<Contact> getContacts(string projectId) {
		Set<Id> conIds = new Set<Id>();
		List<Contact> conList = new List<Contact>();
		if(projectId != null && projectId != ''){
			for(Action_Item__c objAct :[SELECT id, Contact__c from Action_Item__c WHERE Action__r.Project__c =:projectId AND Contact__c != null]){
				conIds.add(objAct.Contact__c);
			}
		}
		if(!conIds.isEmpty()){
			conList = [SELECT Id, Name from Contact where Id IN: conIds];
		}
        
		return conList;
    }
    @AuraEnabled( cacheable = true )
    public static List<AggregateResult> getBrdRules(string projectId) {
        system.debug('getBRD_Ruless');
        
        
        AggregateResult[] brdList = [SELECT count(Id),Module_Progress__r.Module__r.name FROM Question__c where /*Project__c =: projectId and*/ RecordType.name = 'Module' group by Module_Progress__r.Module__r.name];
        system.debug('brdList'+brdList.size());
        return brdList;
        
    }
	
	@AuraEnabled
    public static List<ActionItemWrapper> updateActionItemRec(string recordId, string newAssignee) {
		Action_Item__c actItm = [Select id, Contact__c,Action__r.Project__c from Action_Item__c where id =:recordId];
		actItm.Contact__c = newAssignee;
		system.debug('recordId '+recordId +'==> + ' +' newAssignee '+newAssignee);
		system.debug('actItm '+actItm);
		update actItm;
		
		 
		return fetchActionItems(actItm.Action__r.Project__c);
		
	}
	@AuraEnabled
    public static List<ActionItemWrapper> createContact(string projectId, string firstNameVal,string lastNameVal,string recordId) {
		String accId = [SELECT Client__c from project__c where id=:projectId ].Client__c;
		
		Contact con =  new Contact();
		con.FirstName = firstNameVal;
		con.LastName = lastNameVal;
		con.AccountId = accId;
		insert con;
		
		return updateActionItemRec(recordId,con.Id);
	}
	
    @AuraEnabled
    public static List<ActionItemWrapper> createActionItemResp(string projectId, string inputCommentVal,string recordId) {
		String accId = [SELECT Client__c from project__c where id=:projectId ].Client__c;
		
		Action_Item_Response__c actnItemResp =  new Action_Item_Response__c();
		actnItemResp.Action_Item__c = recordId;
		actnItemResp.Comments__c = inputCommentVal;
		
		insert actnItemResp;
		
		return fetchActionItems(projectId);
	}
	
    
    
    public class ActionItemWrapper {
        
        @AuraEnabled
        public Boolean hideBool;
		@AuraEnabled
        public string iconClicked;
        @AuraEnabled
        public Boolean contactBool;
		@AuraEnabled
        public Boolean toogleBool;
        @AuraEnabled
        public Action_Item__c actionItemObj;

        public ActionItemWrapper( Boolean hideBool, Boolean toogleBool, Action_Item__c actionItemObj, Boolean contactBool, string iconClicked ) {
            
            this.hideBool = hideBool;
            this.actionItemObj = actionItemObj;
            this.contactBool = contactBool;
			this.iconClicked = iconClicked;
			this.toogleBool = toogleBool;
            
        }
        
    }
}