force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Criticality__c.field-meta.xml
<CustomField>
    <fullName>Criticality__c</fullName>
    <label>Criticality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Criticality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>Next_Steps__c</fullName>
    <label>Next Steps</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Question_Choice__c.field-meta.xml
<CustomField>
    <fullName>Question_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Choice</label>
    <referenceTo>Question_Choice__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item__c/Action_Item__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Item__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Criticality__c.field-meta.xml
<CustomField>
    <fullName>Criticality__c</fullName>
    <label>Criticality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Criticality</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Details_to_capture__c.field-meta.xml
<CustomField>
    <fullName>Details_to_capture__c</fullName>
    <label>Details to capture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/New_Assignee__c.field-meta.xml
<CustomField>
    <fullName>New_Assignee__c</fullName>
    <label>New Assignee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZEC_ActionDAO.cls
public class ZEC_ActionDAO {

    public static List<Action__c> getActionWithActionItems_By_Ques_Choice(List<Question_Choice__c> questionChoice){
       return [SELECT Id, Name,Question_Choice__r.name,Question_Choice__r.Question__r.Name, Next_Steps__c,
                      Project__r.name,(Select Id, Action__c, Details_to_capture__c, ETA__c, Response__c, Status__c,
                                       Criticality__c, Contact__c, New_Assignee__c  from Action_Items__r where Details_to_capture__c!= NULL)
                              FROM Action__c where Question_Choice__c in:questionChoice];
    }
}