force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Data_Configured__c.field-meta.xml
<CustomField>
    <fullName>Data_Configured__c</fullName>
    <label>Data Configured</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Screen</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Master__c/Question_Master__c.object-meta.xml
<CustomObject>
    <label>Question Master</label>
    <nameField>
        <label>Question Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Master__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Questions Master</relationshipLabel>
    <relationshipName>Questions_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Master__c/fields/Question_Title__c.field-meta.xml
<CustomField>
    <fullName>Question_Title__c</fullName>
    <label>Question Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Get_Sign_Off__c.field-meta.xml
<CustomField>
    <fullName>Get_Sign_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get Sign Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen_Order__c.field-meta.xml
<CustomField>
    <fullName>Screen_Order__c</fullName>
    <inlineHelpText>Order of displaying the screens</inlineHelpText>
    <label>Screen Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Show_Summary__c.field-meta.xml
<CustomField>
    <fullName>Show_Summary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ZEC_ScreenDataBatch.cls
public class ZEC_ScreenDataBatch implements Database.Batchable<sObject>{
    
    private Project__c projectRecord;
    private Boolean isError;
    
    public ZEC_ScreenDataBatch(String projectId){
        isError = false;
        List<Project__c> projectList = [Select Id, Client__c From Project__c where Id =: projectId];
        if(projectList != null && !projectList.isEmpty()){
            projectRecord = projectList[0];
        }
        System.debug('projectRecord'+projectRecord);
		/*
		listOfScreen = [select Id, Name, Get_Sign_Off__c, Show_Summary__c, Screen_Order__c from Screen__c];  
        listOfModule = [select Id, Screen__c, Name, RecordType.DeveloperName from Module__c];
        listOfQuestionMaster = [select Id, Question_Title__c, Module__c from Question_Master__c];
*/
        
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('Start');
        if(projectRecord == null) {
            return null;
        }
        String query = 'Select Id, Name, Get_Sign_Off__c, Show_Summary__c, Screen_Order__c from Screen__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Screen__c> screenList) {
        System.debug('screenList:'+screenList);
        List<Screen_Progress__c> screenProgressList = new List<Screen_Progress__c>();
        for(Screen__c screen : screenList){
            Screen_Progress__c screenProgress = new Screen_Progress__c();
            screenProgress.Name = screen.Name;
            screenProgress.Get_Sign_Off__c = screen.Get_Sign_Off__c;
            screenProgress.Show_Summary__c = screen.Show_Summary__c;
            screenProgress.Screen_Order__c = screen.Screen_Order__c;
            screenProgress.Screen__c = screen.Id;
            screenProgress.Account__c = projectRecord.Client__c;
            screenProgress.Project__c = projectRecord.Id;
            screenProgressList.add(screenProgress);
        }
        try {
            System.debug('screenProgressList:'+screenProgressList);
            if(!screenProgressList.isEmpty() && !isError){
            	insert screenProgressList;   
            }
        } catch(Exception e) {
            isError = true;
            System.debug(e);
            throw e;
        }
        
    }   
    
    public void finish(Database.BatchableContext BC) {
        if(projectRecord != null){
            if(isError){
                //Create a delete batch for this
				delete [Select Id, Screen__c From Screen_Progress__c where Project__c =: projectRecord.Id];                
            }
            else{
				projectRecord.Data_Configured__c = projectRecord.Data_Configured__c+';Screen';
        		update projectRecord;
                ZEC_ModuleDataBatch moduleDataBatch = new ZEC_ModuleDataBatch(projectRecord);
                Database.executeBatch(moduleDataBatch);
            }
        }
  	}
}