force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Screen_Progress__c.field-meta.xml
<CustomField>
    <fullName>Screen_Progress__c</fullName>
    <label>Screen Progress</label>
    <referenceTo>Screen_Progress__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Question_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Master</label>
    <referenceTo>Question_Master__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/Question_Choice__c.object-meta.xml
<CustomObject>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice__c/fields/Question_Choice_Master__c.field-meta.xml
<CustomField>
    <fullName>Question_Choice_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Choice Master</label>
    <referenceTo>Question_Choice_Master__c</referenceTo>
    <relationshipLabel>Question Choices</relationshipLabel>
    <relationshipName>Question_Choices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Choice_Master__c/Question_Choice_Master__c.object-meta.xml
<CustomObject>
    <label>Question Choice Master</label>
    <nameField>
        <label>Question Choice Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Choice Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Choice_Master__c/fields/Question_Master__c.field-meta.xml
<CustomField>
    <fullName>Question_Master__c</fullName>
    <label>Question Master</label>
    <referenceTo>Question_Master__c</referenceTo>
    <relationshipLabel>Questions Choice Master</relationshipLabel>
    <relationshipName>Questions_Choice_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Master__c/Question_Master__c.object-meta.xml
<CustomObject>
    <label>Question Master</label>
    <nameField>
        <label>Question Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Master__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Questions Master</relationshipLabel>
    <relationshipName>Questions_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZEC_QuestionChoiceDataBatch.cls
public class ZEC_QuestionChoiceDataBatch implements Database.Batchable<sObject>{
	public Project__c projectRecord;
    private Map<Id, Question__c> questionMap = new Map<Id, Question__c>();
    
    public ZEC_QuestionChoiceDataBatch(Project__c projectRecord){
        this.projectRecord = projectRecord;
        Set<Id> moduleIds = new Set<Id>();
        List<Module_Progress__c> moduleProgressList = [Select Id, Module__c From Module_Progress__c where Screen_Progress__r.Project__c =: projectRecord.Id];
        for(Module_Progress__c moduleProgress : moduleProgressList){
            moduleIds.add(moduleProgress.Id);
        }
        List<Question__c> questionList = [Select Id, Question_Master__c From Question__c Where Module_Progress__c in : moduleIds];
        for(Question__c question : questionList){
            questionMap.put(question.Question_Master__c, question);
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select Id from Question_Choice_Master__c where Question_Master__c in :'+questionMap.keySet();
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Question_Choice_Master__c> questionChoiceMasterList) {
        List<Question_Choice__c> questionChoiceList = new List<Question_Choice__c>();
        for(Question_Choice_Master__c questionChoiceMaster: questionChoiceMasterList){
            Question_Choice__c questionChoice = new Question_Choice__c();
            questionChoice.Question__c = questionMap.get(questionChoiceMaster.Question_Master__c).Id;
            questionChoiceList.add(questionChoice);
        }
        try {
            if(!questionChoiceList.isEmpty()){
            	insert questionChoiceList;   
            }
        } catch(Exception e) {
            System.debug(e);
            throw e;
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
}