force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <label>Module</label>
</RecordType>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Screen_Progress__c.field-meta.xml
<CustomField>
    <fullName>Screen_Progress__c</fullName>
    <label>Screen Progress</label>
    <referenceTo>Screen_Progress__c</referenceTo>
    <relationshipLabel>Modules Progress</relationshipLabel>
    <relationshipName>Modules_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Data_Configured__c.field-meta.xml
<CustomField>
    <fullName>Data_Configured__c</fullName>
    <label>Data Configured</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Screen</fullName>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/Screen_Progress__c.object-meta.xml
<CustomObject>
    <label>Screen Progress</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screen Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screen_Progress__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Screen Progresses</relationshipLabel>
    <relationshipName>Screen_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZEC_ModuleDataBatch.cls
public class ZEC_ModuleDataBatch implements Database.Batchable<sObject>{
    
    public Project__c projectRecord;
    private Map<Id, Screen_Progress__c> screenProgressMap = new Map<Id, Screen_Progress__c>();
    
    public ZEC_ModuleDataBatch(Project__c projectRecord){
        this.projectRecord = projectRecord;
        List<Screen_Progress__c> screenProgressList = [Select Id, Screen__c From Screen_Progress__c where Project__c =: projectRecord.Id];
        for(Screen_Progress__c screenProgress : screenProgressList){
            screenProgressMap.put(screenProgress.Screen__c, screenProgress);
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select Id, Screen__c, Name, RecordType.DeveloperName from Module__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Module__c> moduleList) {
        List<Screen_Progress__c> moduleProgressList = new List<Screen_Progress__c>();
        for(Module__c module : moduleList){
            Module_Progress__c moduleProgress = new Module_Progress__c();
            moduleProgress.Name = module.Name;
            moduleProgress.Screen_Progress__c = screenProgressMap.get(module.Screen__c).Id;
        }
        try {
            if(!moduleProgressList.isEmpty()){
            	insert moduleProgressList;   
            }
        } catch(Exception e) {
            System.debug(e);
            throw e;
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        if(projectRecord != null){
            projectRecord.Data_Configured__c = projectRecord.Data_Configured__c+';Module';
        	update projectRecord;
            ZEC_QuestionDataBatch questionDataBatch = new ZEC_QuestionDataBatch(projectRecord);
            Database.executeBatch(questionDataBatch);
        }
    }

}