force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Screen</label>
    <referenceTo>Screen__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <label>Module</label>
</RecordType>

force-app/main/default/objects/Question_Master__c/Question_Master__c.object-meta.xml
<CustomObject>
    <label>Question Master</label>
    <nameField>
        <label>Question Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Master__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Questions Master</relationshipLabel>
    <relationshipName>Questions_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Master__c/fields/Question_Title__c.field-meta.xml
<CustomField>
    <fullName>Question_Title__c</fullName>
    <label>Question Title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Master__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZEC_QuestionBankController.cls
public class ZEC_QuestionBankController {
	
	public static final string TOGGLE_ICON = 'utility:chevronright';
	
	@AuraEnabled (cacheable=true)
    public static List<Module__c> getModules(){
        return [SELECT Id, Name FROM Module__c ];
    }
    @AuraEnabled (cacheable=true)
    public static List<Screen__c> getScreens(){
        return [SELECT Id, Name FROM Screen__c];
    }
    @AuraEnabled
    public static void saveQuestion(string questionLabel, string module, string questionName){
        Question_Master__c qm = new Question_Master__c();
        qm.Question_Title__c = questionLabel;
        qm.Name = questionName;
        qm.Module__c = module;
        insert qm;
    }
    @AuraEnabled
    public static List<QuestionBankWrapper> getQuestionMaster(){
        //return [select id, name, module__r.Screen__r.Name, module__r.Name, Module__r.Category__c, Question_Type__c, Question_Title__c from Question_Master__c];
		
		
        List<QuestionBankWrapper> questnBnkWrap = new List< QuestionBankWrapper >();
         
		for ( Question_Master__c qm : [select id, name, module__r.Screen__r.Name, module__r.Name, Module__r.Category__r.Name, Question_Type__c, Question_Title__c from 								Question_Master__c order by lastModifiedDate desc ] ) {
																					 
										 //QuestionBankWrapper objWrap = new QuestionBankWrapper( true, actionItem, actionItem.Contacts.size() > 0 ? true : false );
										 QuestionBankWrapper objWrap = new QuestionBankWrapper( true, false, qm, /* true , */TOGGLE_ICON);
										 questnBnkWrap.add( objWrap );
																					 
		}
        
        return questnBnkWrap;
		
    }
	public class QuestionBankWrapper {
        
        @AuraEnabled
        public Boolean hideBool;
		@AuraEnabled
        public string iconClicked;
        /* @AuraEnabled
        public Boolean contactBool; */
		@AuraEnabled
        public Boolean toogleBool;
        @AuraEnabled
        public Question_Master__c questObj;

        public QuestionBankWrapper( Boolean hideBool, Boolean toogleBool, Question_Master__c questObj, /* Boolean contactBool, */ string iconClicked ) {
            
            this.hideBool = hideBool;
            this.questObj = questObj;
            //this.contactBool = contactBool;
			this.iconClicked = iconClicked;
			this.toogleBool = toogleBool;
            
        }
        
    }
}